### ISSUE TITLE
sugetão

### ISSUE THREAD

**Issue by eutheuzin7** [Rodrigofms/jogo-dos-pares#1]
alguns emoji bugado no pc, e tem um emoji que sai para fora da tela. também recomendaria adicionar um tempo de espera entre cada par de carta aberta, fora isso está ótimo!

**Comment by Rodrigofms** [comment]
Obrigado por avisar do bug, não fazia ideia que tinha um pois como fiz no Windows 11, aqui funcionava normalmente. troquei os emojis e creio eu que agora os bugs em relação a isso acabaram
